//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "medlem")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub pid: Uuid,
    pub name: String,
    #[sea_orm(unique)]
    pub email: String,
    pub phone_nr: Option<String>,
    pub address: Option<String>,
    pub city: Option<String>,
    pub birthdate: Option<Date>,
    pub status: String,
    pub user_pid: Option<Uuid>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub parents_pid: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub previous_partners: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub children_pid: Option<Json>,
    pub partner_pid: Option<Uuid>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
